name: Generate ASCII
on: push


jobs:
  build_job:

     runs-on: ubuntu-latest
     steps:
       - name: Checkout repo
         uses: actions/checkout@v7
       - name: build app
         run: cowsay -f dragon "Run for cover, I am a dragon ... RAWR" >> dragon.txt
     #  - name: Executing shell script.
    #     run: sh ./script.sh
         
    #   - name: list files
    #     run: ls 
    #   - name: Read files
    #     run: cat README.md
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run: ls -ltr
  deploy_job:
    runs-on: ubuntu-latest:
    steps:
      - name: Read file
        run: cat  dragon.txt  