name: test pipeline
on: push
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
    - name: Check uptime of runner
      run: uptime
    - name: create a file
      run: echo "test" > text.txt
    - name: upload artifacts
      uses: actions/upload-artifact@v7
      with: 
        name: my-a
        path: text.txt
    
  test-job:
    needs: build-job
    runs-on: ubuntu-latest
    steps:
    - name: download artifacts
      uses: actions/download-artifact@v7
      with:
         name: my-a
    - name: read file
      run: cat text.txt