name: Revise pipeline knowledge
on: push
jobs:
    test-job:
        runs-on: ubuntu-latest
        steps:
            - name: check uptime of runner
              run: uptime
            - name: create a file
              run: echo "test" > test.txt
            - name: list the files and content
              run: |
               ls -ld
               cat test.txt